name: PyDoll Tests

on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.2"
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 132
      - name: Run tests with coverage
        run: |
          uv run pytest -s -x --cov=pydoll -vv --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: tests
          name: PyDoll Tests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
